baseURL = ''
languageCode = 'en-us'
title = 'Red Mage Engineer'

disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = true



[markup]
  [markup.highlight]
    guessSyntax = false
    noClasses = true
    noHl = false
    style = 'dracula'
