baseURL = ''
languageCode = 'en-us'
title = 'Red Mage Engineer'

disableKinds = ["taxonomy", "taxonomyTerm"]
enableRobotsTXT = true



[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'dracula'